version: '3.5'
networks:
  backend_net:
    name: bridge_between_frontend_backend
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.96.0/20
          gateway: 192.168.96.1
services:
  backend_sl:
    # The "_" is not allowed in the HOST name as per RFC 1034/1035
    # and that was what was causing the Invalid HTTP_HOST header
    # so replace it with '-'
    # for use this container in the frontend
    container_name: backend-sl
    build:
      context: ./backend_sl # but the source path that we will search about docker image from it
      dockerfile: development.Dockerfile
    restart: always
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=backend_sl.settings.development
      - DEBUG=True
    ports:
      - "6123:6123"
    volumes:
      - static_vol:/app/static # /app: workdir that we created in docker image and move our files in it
      - media_vol:/app/media
    networks:
      - backend_net
    depends_on:
      - redis

# this don't work with version 3.5 maybe work on version 2
#    networks:
#      backend_net:
#        - ipv4_address: 192.168.96.2


  redis:
    container_name: redis-server-api
    image: redis:alpine
    restart: always
    ports:
      - '6379:6379'
    networks:
      - backend_net


  celery:
    container_name: celery-api
    restart: always
    build:
      context: ./backend_sl
      dockerfile: development.Dockerfile
    command: celery -A backend_sl worker -B -E --scheduler django -l info # -B: for turn on the beat
    volumes:
      - celery:/app
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=backend_sl.settings.development
    depends_on:
      - redis
      - backend_sl
    networks:
      - backend_net



volumes:
  static_vol:
  media_vol:
  celery: