# Generated by Django 4.0 on 2022-10-13 15:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_notification_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 13, 18, 50, 27, 267575)),
        ),
    ]
